//Destroy.....
//personalizado por Emmax-kun 
const roles = {
    '*Humano I*💮': 0,
  '*Humano II*💮': 2,
  '*Humano III*💮': 4,
  '*Humano IV*💮': 6,
  '*Humano V*💮': 8,
  '*Alma en pena I*👻': 10,
  '*Alma en pena II*👻': 12,
  '*Alma en pena III*👻': 14,
  '*Alma en pena IV*👻': 16,
  '*Alma en pena V*👻': 18,
  '*Alma del infierno I*⚰️': 20,
  '*Alma del infierno II*⚰️': 22,
  '*Alma del infierno III*⚰️': 24,
  '*Alma del infierno IV*⚰️': 26,
  '*Alma del infierno V*⚰️': 28,
  '*Alma del cielo I*🌸': 30,
  '*Alma del cielo II*🌸': 32,
  '*Alma del cielo III*🌸': 34,
  '*Alma del cielo  IV*🌸': 36,
  '*Alma del cielo  V*🌸': 38,
  '*Demonio desterrado I* 🖤': 40,
  '*Demonio desterrado II* 🖤': 42,
  '*Demonio desterrado III* 🖤': 44,
  '*Demonio desterrado IV* 🖤': 46,
  '*Demonio desterrado V* 🖤': 48,
  '*Angel desterrado/a I*🥀': 50,
  '*Angel desterrado/a II*🥀': 52,
  '*Angel desterrado/a III*🥀': 54,
  '*Angel desterrado/a IV*🥀': 56,
  '*Angel desterrado/a V*🥀': 58,
  '*Esclavo de alastor I*♦️': 60,
  '*Esclavo de alastor  II*♦️': 62,
  '*Esclavo de alastor  III*♦️': 64,
  '*Esclavo de alastor  IV*♦️': 66,
  '*Esclavo de alastor V*♦️': 68,
  '*Mascota de alastor I*🐉': 70,
  '*Mascota de alastor II*🐉': 72,
  '*Mascota de alastor III*🐉': 74,
  '*Mascota de alastor IV*🐉': 76,
  '*Mascota de alastor V*🐉': 78,
  '*Alastor human I*😈': 80,
  '*Alastor human II*😈': 85,
  '*Alastor human III*😈': 90,
  '*Alastor human IV*😈': 95,
  '*Alastor human V*😈': 99,
  '*Alastor demoníaco I*💢': 100,
  '*Alastor demoníaco II*💢': 110,
  '*Alastor demoníaco III*💢': 120,
  '*Alastor demoníaco IV*💢': 130,
  '*Alastor demoniaco V*💢': 140,
  '*Comandante de los ángeles I*🦅': 150,
  '*Comandante de los ángeles II*🦅': 160,
  '*Comandante de los angeles III*🦅': 170,
  '*Comandante de los angeles  IV*🦅': 180,
  '*Comandante de los angeles V*🦅': 199,
  '*Comandante de las almas I*🦇': 200,
  '*Comandante de las almas II*🦇': 225,
  '*Comandante de las almas III*🦇': 250,
  '*Comandante de las almas IV*🦇': 275,
  '*Comandante de las almas V*🦇': 299,
  '*Exterminador/a de ángeles I*🔪': 300,
  '*Exterminador/a de ángeles II*🔪': 325,
  '*Exterminador/a de angeles III*🔪': 350,
  '*Exterminador/a de ángeles IV*🔪': 375,
  '*Exterminador/a de ángeles V*🔪': 399,
  '*Exterminador/a de pecados I*☠️': 400,
  '*Exterminador/a de pecados II*☠️': 425,
  '*Exterminador/a de pecados  III*☠️': 450,
  '*Exterminador/a de pecados IV*☠️': 475,
  '*Exterminador/a de pecados V*☠️': 499,
  '*Protector/a del infierno I*✡️': 500,
  '*Protector/a del infierno II*✡️': 525,
  '*Protector/a del infierno III*✡️': 550,
  '*Protector/a del infierno IV*✡️': 575,
  '*Protector/a del infierno V*✡️': 599,
  '*Protector/a del cielo I*☁️': 600,
  '*Protector/a del cielo II*☁️': 625,
  '*Protector/a del cielo III*☁️': 650,
  '*Protector/a del cielo IV*☁️': 675,
  '*Protector/a del cielo V*☁️': 699,
  '*Serafin I*🪽': 700,
  '*Serafin II*🪽': 725,
  '*Serafin III*🪽': 750,
  '*Serafin IV*🪽': 775,
  '*Serafin V*🪽': 799,
  '*Pecador I*👿': 800,
  '*Pecador II*👿': 825,
  '*Pecador III*👿': 850,
  '*Pecador IV*👿': 875,
  '*Pecador  V*👿': 899,
  '*Pecado capital I*🌟': 900,
  '*Pecado capital II*🌟': 925,
  '*Pecado capital III*🌟': 950,
  '*Pecado capital IV*🌟': 975,
  '*Pecado capital V*🌟': 999,
  '*🌟 Serafin mayor 🌟*': 1000,
  '*🌟 Eva 🌟*': 20000,
  '*🌟 Adan 🌟*': 300000,
  '*🌟 Lucifer 🌟*': 400000,
  '*🌟 Dios  🌟*': 500000000,
  '*👑 Alastor forma definitiva  👑*': 100000000000000
}

let handler = m => m
handler.before = async function (m, { conn }) {
  let user = db.data.users[m.sender]
  if (!user) return
  let level = user.level
  let role = (Object.entries(roles).sort((a, b) => b[1] - a[1]).find(([, minLevel]) => level >= minLevel) || Object.entries(roles)[0])[0]
  user.role = role
  return true
}
export default handler